services:

  frontend:
    build:
      context: frontend/platform
      dockerfile: Dockerfile

  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]



  redis:
    image: redis/redis-stack:latest
    ports:
       - "8001:8001"
       - "6379:6379"
    volumes:
      - redis_volume:/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8002:80"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=12345
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False

    depends_on:
      - postgres


  backend:
    build:
      context: ./backend
      dockerfile: ./web.Dockerfile

    volumes:
      - ./backend/src/web:/src/web
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy


  service_calendar:
    build:
      context: ./backend
      dockerfile: ./calendar.Dockerfile
    volumes:
      - ./backend/src/service_calendar:/src/service_calendar
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy



  frontend_calendar:
      build:
        context: frontend/calendar
        dockerfile: Dockerfile


  

  worker:
   build:
     context: ./backend
     dockerfile: worker.Dockerfile
   env_file:
     - ./.env
   environment:
     POSTGRES_HOST: postgres
     REDIS_HOST: redis

   ports:
     - "8080:8080"

   depends_on:
     redis:
       condition: service_started
     postgres:
       condition: service_healthy






  nginx:
   image: nginx:latest
   ports:
     - "80:80"
   volumes:
     - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
     - ./nginx/cors.conf:/etc/nginx/cors.conf
     - ./backend/src/web/app/static:/www/data
   depends_on:
     - backend
     - frontend
     - frontend_calendar
     - service_calendar



volumes:
  redis_volume: {}
  pgdata: {}
  pgadmin_volume: