"""empty message

Revision ID: 54b52b1c303b
Revises: d884b6d68cdc
Create Date: 2024-12-07 01:32:16.504842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '54b52b1c303b'
down_revision: Union[str, None] = 'd884b6d68cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('federation_region_representations')
    op.add_column('region_representations', sa.Column('federal_district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'region_representations', 'representations', ['federal_district_id'], ['id'])
    op.drop_column('representation_stuff', 'is_logged_in')
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representation_stuff', sa.Column('is_logged_in', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'region_representations', type_='foreignkey')
    op.drop_column('region_representations', 'federal_district_id')
    op.create_table('federation_region_representations',
    sa.Column('federal_district_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_representation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['federal_district_id'], ['representations.id'], name='federation_region_representations_federal_district_id_fkey'),
    sa.ForeignKeyConstraint(['region_representation_id'], ['region_representations.id'], name='federation_region_representations_region_representation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='federation_region_representations_pkey')
    )
    # ### end Alembic commands ###
