"""empty message

Revision ID: 5ae6e9d5e947
Revises: 676690b8aca4
Create Date: 2024-12-07 23:46:30.133111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '5ae6e9d5e947'
down_revision: Union[str, None] = '676690b8aca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_solutions',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_teams')
    op.add_column('teams', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('teams', sa.Column('created_at', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('about', sa.String(), nullable=False))
    op.create_foreign_key(None, 'teams', 'events', ['event_id'], ['id'])
    op.drop_column('teams', 'max_members')
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    op.add_column('teams', sa.Column('max_members', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'about')
    op.drop_column('teams', 'created_at')
    op.drop_column('teams', 'event_id')
    op.create_table('user_teams',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='user_teams_team_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_teams_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_teams_pkey')
    )
    op.drop_table('team_solutions')
    # ### end Alembic commands ###
