"""empty message

Revision ID: 6197cee554c4
Revises: e8295acbe88e
Create Date: 2024-12-11 21:31:20.553499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '6197cee554c4'
down_revision: Union[str, None] = 'e8295acbe88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_solutions', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team_solutions', 'events', ['event_id'], ['id'])
    op.add_column('teams', sa.Column('photo_url', sa.String(), nullable=True))
    op.alter_column('teams', 'about',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'about',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('teams', 'photo_url')
    op.drop_constraint(None, 'team_solutions', type_='foreignkey')
    op.drop_column('team_solutions', 'event_id')
    # ### end Alembic commands ###
