"""empty message

Revision ID: 768e3638a72a
Revises: b986f74f29a6
Create Date: 2024-12-08 03:54:25.223930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

from web.alembic.seed import seed_db

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '768e3638a72a'
down_revision: Union[str, None] = 'b986f74f29a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    async def wrapper(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        await seed_db(session)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(wrapper)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
