"""empty message

Revision ID: e951a4b06046
Revises: bcb97535106e
Create Date: 2024-12-07 15:24:22.872059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = 'e951a4b06046'
down_revision: Union[str, None] = 'bcb97535106e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('suggestions', sa.Column('age', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'age')
    op.drop_column('suggestions', 'name')
    # ### end Alembic commands ###
