"""empty message

Revision ID: f36a8a52078d
Revises: 64388d1d97cf
Create Date: 2024-12-07 17:48:49.181563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = 'f36a8a52078d'
down_revision: Union[str, None] = '64388d1d97cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'suggestions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#       Factory.__async_session__ = session
#       await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'suggestions', type_='foreignkey')
    op.drop_column('suggestions', 'user_id')
    # ### end Alembic commands ###
