name: Deploy to Server

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_KEY_JSON }}

      - name: Build image
        run: docker compose build

      - name: Push image
        run: docker compose push

      - name: SSH and run commands
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Reference the private key stored in GitHub Secrets
        run: |
          echo "$PRIVATE_KEY" > private_key.pem # Write the private key to a file
          chmod 600 private_key.pem # Set the appropriate permissions for the key file

          # Establish an SSH connection and execute commands on the remote server
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@centrifugo.tech <<EOF
            cd /home/ubuntu/deploy
            docker compose pull
            docker compose up -d
          EOF

          rm -f private_key.pem # Remove the private key file after use for security

      


    