name: Deploy to Server

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and run commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/deploy
            git pull origin main
            docker compose down
            docker compose up -d --build

      


    